### ISSUE TITLE
Error in chunk manifest[entry]

### ISSUE THREAD

**Issue by GoDotDotDot** [soundcloud/chunk-manifest-webpack-plugin#45]
When I run `npm run dev` with my `webpack.config.js`,I see thoes error info:
```javascript
ERROR in chunk manifest [entry]
js/[name]-[chunkhash].bundle.js
Chunk.entry was removed. Use hasRuntime()
Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Chunk.js:49:9)
    at registerChunk (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\chunk-manifest-webpack-plugin\lib\ChunkManifestPlugin.js:28:73)
    at Array.reduce (native)
    at registerChunk (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\chunk-manifest-webpack-plugin\lib\ChunkManifestPlugin.js:36:27)
    at Array.reduce (native)
    at MainTemplate.<anonymous> (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\chunk-manifest-webpack-plugin\lib\ChunkManifestPlugin.js:25:33)
    at MainTemplate.applyPluginsWaterfall (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:92:24)
    at MainTemplate.plugin (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\MainTemplate.js:106:31)
    at MainTemplate.applyPluginsWaterfall (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:92:24)
    at MainTemplate.render (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\MainTemplate.js:175:31)
    at Compilation.createChunkAssets (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Compilation.js:1254:34)
    at sealPart2 (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Compilation.js:629:10)
    at next (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:184:11)
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:241:13
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:421:16
    at iteratorCallback (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:998:13)
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:906:16
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:224:15
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:421:16
    at eachOfArrayLike (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:991:9)
    at eachOf (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:3145:5)
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:189:29
    at D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:3083:16
    at eachOfArrayLike (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:1003:9)
    at eachOf (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\async\dist\async.js:3145:5)
    at Compilation.<anonymous> (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\extract-text-webpack-plugin\dist\index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\tapable\lib\Tapable.js:188:13)
    at Compilation.seal (D:\CHUKUI\WORK\PROJECTS\MD-PRO02\node_modules\webpack\lib\Compilation.js:579:8)
```
Adn my project repo on there [click here](https://github.com/MeteDesign/Webpack)

Who can help me to resolve this?thanks.

**Comment by ramrami** [comment]
I already opened an issue for this problem #43 . Downgrading to v1.1.0 worked for me.

**Comment by SpainTrain** [comment]
fixed in 1.1.2
